name: Destruktief
favicon: null
layout_spectrum: 1
typography_spectrum: 0.22506847837939858
title: 'Het ongewone netwerk '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f5f7f4'
    - '#0b0b7b'
    - '#71f6f3'
    - '#5b5ca6'
    - '#c9cc67'
  brandStrength: 0.10406440286897123
  lightness: 0.07770204450935125
  saturation: 0.9191409153863788
  rhythmicContrast: 0.906752118607983
purpose: []
